logging:
  level:
    org:
      springframework:
        cloud: debug
        web: debug
server:
  port: 8888
spring:
  application:
    name: mssc-brewery-config
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/fykidwai/mssc-brewery-config-repo
          default-label: main
          search-paths:
          - '{application}'

# Should be env property
encrypt:
  key: MySuperSecretKey